public class Flexer extends freditor.Flexer {
    public static final Flexer instance = new Flexer();

    public static final int END = 0;
    public static final int ERROR = -1;

    public static final int NEWLINE = -2;
    public static final int FIRST_SPACE = -3;
    public static final int NEXT_SPACE = 1;

    public static final int COMMENT_FIRST = -4;
    public static final int COMMENT_NEXT = 2;

    public static final int CHAR_CONSTANT_BEGIN = -5;
    public static final int CHAR_CONSTANT_INSIDE = 3;
    public static final int CHAR_CONSTANT_END = 4;

    public static final int STRING_LITERAL_BEGIN = -6;
    public static final int STRING_LITERAL_ESCAPE = 5;
    public static final int STRING_LITERAL_INSIDE = 6;
    public static final int STRING_LITERAL_END = 7;

    public static final int FIRST_DIGIT = -7;
    public static final int NEXT_DIGIT = 8;

    public static final int IDENTIFIER_FIRST = -8;
    public static final int IDENTIFIER_NEXT = 9;

    // auto-generated by freditor.FlexerGenerator
    public static final int HASH = -9;
    public static final int HASH_QUESTION = 10;
    public static final int HASH_QUESTION_AT = 11;
    public static final int PERCENT = -10;
    public static final int APOSTROPHE = -11;
    public static final int OPENING_PAREN = -12;
    public static final int CLOSING_PAREN = -13;
    public static final int LESS = -14;
    public static final int LESS_EQUAL = 12;
    public static final int EQUAL = -15;
    public static final int EQUAL_EQUAL = 13;
    public static final int MORE = -16;
    public static final int MORE_EQUAL = 14;
    public static final int AT = -17;
    public static final int OPENING_BRACKET = -18;
    public static final int CLOSING_BRACKET = -19;
    public static final int CARET = -20;
    public static final int GRAVE = -21;
    public static final int OPENING_BRACE = -22;
    public static final int CLOSING_BRACE = -23;
    public static final int TILDE = -24;
    public static final int TILDE_AT = 15;

    @Override
    public int pickColorForLexeme(int endState) {
        switch (endState) {
            default:
                return 0x000000;

            case ERROR:

            case CHAR_CONSTANT_BEGIN:
            case CHAR_CONSTANT_INSIDE:

            case STRING_LITERAL_BEGIN:
            case STRING_LITERAL_ESCAPE:
            case STRING_LITERAL_INSIDE:
                return 0x808080;

            case COMMENT_FIRST:
            case COMMENT_NEXT:
                return 0x008000;

            case CHAR_CONSTANT_END:
            case STRING_LITERAL_END:
                return 0xdc009c;

            case FIRST_DIGIT:
            case NEXT_DIGIT:
                return 0x6400c8;

            case OPENING_PAREN:
            case CLOSING_PAREN:
            case OPENING_BRACKET:
            case CLOSING_BRACKET:
            case OPENING_BRACE:
            case CLOSING_BRACE:
                return 0xff0000;
/*
            case ASSERT:
            case AUTO:
            case BREAK:
            case CASE:
            case CONST:
            case CONTINUE:
            case DEFAULT:
            case ELSE:
            case ENUM:
            case EXTERN:
            case FOR:
            case GOTO:
            case IF:
            case REGISTER:
            case RETURN:
            case SIZEOF:
            case STATIC:
            case STRUCT:
            case SWITCH:
            case TYPEDEF:
            case UNION:
            case VOLATILE:
            case WHILE:
                return 0x0000ff;

            case CHAR:
            case DOUBLE:
            case FLOAT:
            case INT:
            case LONG:
            case SHORT:
            case SIGNED:
            case UNSIGNED:
            case VOID:
                return 0x008080;
*/
            case HASH:
            case HASH_QUESTION:
            case HASH_QUESTION_AT:
            case PERCENT:
            case APOSTROPHE:
            case LESS:
            case LESS_EQUAL:
            case EQUAL:
            case EQUAL_EQUAL:
            case MORE:
            case MORE_EQUAL:
            case AT:
            case CARET:
            case GRAVE:
            case TILDE:
            case TILDE_AT:
                return 0x804040;
        }
    }

    @Override
    protected int nextStateOrEnd(int currentState, char input) {
        switch (currentState) {
            default:
                throw new AssertionError("unhandled lexer state " + currentState + " for input " + input);
            case END:
            case ERROR:
            case NEWLINE:
            case CHAR_CONSTANT_END:
            case STRING_LITERAL_END:

// auto-generated by freditor.FlexerGenerator
            case HASH_QUESTION_AT:
            case PERCENT:
            case APOSTROPHE:
            case OPENING_PAREN:
            case CLOSING_PAREN:
            case LESS_EQUAL:
            case EQUAL_EQUAL:
            case MORE_EQUAL:
            case AT:
            case OPENING_BRACKET:
            case CLOSING_BRACKET:
            case CARET:
            case GRAVE:
            case OPENING_BRACE:
            case CLOSING_BRACE:
            case TILDE_AT:
                switch (input) {
                    default:
                        return ERROR;

                    case '\n':
                        return NEWLINE;
                    case ' ':
                    case ',':
                        return FIRST_SPACE;

                    case ';':
                        return COMMENT_FIRST;

                    case '\\':
                        return CHAR_CONSTANT_BEGIN;
                    case '\"':
                        return STRING_LITERAL_BEGIN;

                    case '0':
                    case '1':
                    case '2':
                    case '3':
                    case '4':
                    case '5':
                    case '6':
                    case '7':
                    case '8':
                    case '9':
                        return FIRST_DIGIT;

                    case 'A':
                    case 'B':
                    case 'C':
                    case 'D':
                    case 'E':
                    case 'F':
                    case 'G':
                    case 'H':
                    case 'I':
                    case 'J':
                    case 'K':
                    case 'L':
                    case 'M':
                    case 'N':
                    case 'O':
                    case 'P':
                    case 'Q':
                    case 'R':
                    case 'S':
                    case 'T':
                    case 'U':
                    case 'V':
                    case 'W':
                    case 'X':
                    case 'Y':
                    case 'Z':

                    case 'a':
                    case 'b':
                    case 'c':
                    case 'd':
                    case 'e':
                    case 'f':
                    case 'g':
                    case 'h':
                    case 'i':
                    case 'j':
                    case 'k':
                    case 'l':
                    case 'm':
                    case 'n':
                    case 'o':
                    case 'p':
                    case 'q':
                    case 'r':
                    case 's':
                    case 't':
                    case 'u':
                    case 'v':
                    case 'w':
                    case 'x':
                    case 'y':
                    case 'z':

                    case '!':
                    case '*':
                    case '+':
                    case '-':
                    case '?':
                    case '_':

                    case ':':
                    case '.':
                    case '/':
                        return IDENTIFIER_FIRST;

// auto-generated by freditor.FlexerGenerator
                    case '#':
                        return HASH;
                    case '%':
                        return PERCENT;
                    case '\'':
                        return APOSTROPHE;
                    case '(':
                        return OPENING_PAREN;
                    case ')':
                        return CLOSING_PAREN;
                    case '<':
                        return LESS;
                    case '=':
                        return EQUAL;
                    case '>':
                        return MORE;
                    case '@':
                        return AT;
                    case '[':
                        return OPENING_BRACKET;
                    case ']':
                        return CLOSING_BRACKET;
                    case '^':
                        return CARET;
                    case '`':
                        return GRAVE;
                    case '{':
                        return OPENING_BRACE;
                    case '}':
                        return CLOSING_BRACE;
                    case '~':
                        return TILDE;
                }
            case FIRST_SPACE:
            case NEXT_SPACE:
                switch (input) {
                    case ' ':
                    case ',':
                        return NEXT_SPACE;
                    default:
                        return END;
                }
            case COMMENT_FIRST:
            case COMMENT_NEXT:
                switch (input) {
                    case '\n':
                        return END;
                    default:
                        return COMMENT_NEXT;
                }
            case CHAR_CONSTANT_BEGIN:
            case CHAR_CONSTANT_INSIDE:
                return Character.isLetterOrDigit(input) ? CHAR_CONSTANT_INSIDE : CHAR_CONSTANT_END;

            case STRING_LITERAL_BEGIN:
            case STRING_LITERAL_INSIDE:
                switch (input) {
                    case '\\':
                        return STRING_LITERAL_ESCAPE;
                    default:
                        return STRING_LITERAL_INSIDE;
                    case '\"':
                        return STRING_LITERAL_END;
                }
            case STRING_LITERAL_ESCAPE:
                switch (input) {
                    default:
                        return STRING_LITERAL_INSIDE;
                    case '\n':
                        return ERROR;
                }
            case FIRST_DIGIT:
            case NEXT_DIGIT:
                switch (input) {
                    case '0':
                    case '1':
                    case '2':
                    case '3':
                    case '4':
                    case '5':
                    case '6':
                    case '7':
                    case '8':
                    case '9':
                    case '.':
                    case 'X':
                    case 'x':
                    case 'A':
                    case 'a':
                    case 'B':
                    case 'b':
                    case 'C':
                    case 'c':
                    case 'D':
                    case 'd':
                    case 'E':
                    case 'e':
                    case 'F':
                    case 'f':
                        return NEXT_DIGIT;
                    default:
                        return END;
                }
            case IDENTIFIER_FIRST:
            case IDENTIFIER_NEXT:
                return identifier(input);

            case HASH:
                return operator('?', HASH_QUESTION, input);
            case HASH_QUESTION:
                return operator('@', HASH_QUESTION_AT, input);
            case LESS:
                return operator('=', LESS_EQUAL, input);
            case EQUAL:
                return operator('=', EQUAL_EQUAL, input);
            case MORE:
                return operator('=', MORE_EQUAL, input);
            case TILDE:
                return operator('@', TILDE_AT, input);
        }
    }

    @Override
    protected int identifier(char input) {
        switch (input) {
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':

            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':

            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':

            case '!':
            case '\'':
            case '*':
            case '+':
            case '-':
            case '?':
            case '_':

            case ':':
            case '.':
            case '/':
                return IDENTIFIER_NEXT;

            default:
                return END;
        }
    }
}
